### ISSUE TITLE
cannot load such file -- shopify_api (LoadError)

### ISSUE THREAD

**Issue by zamtech18** [Shopify/example-ruby-app#20]
I am following [these instructions](https://help.shopify.com/api/tutorials/building-public-app) for the basic shopify app setup and I am getting this error.

C:/Ruby24-x64/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:59:in `require': cannot load such file -- shopify_api (LoadError)
        from C:/Ruby24-x64/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:59:in `require'
        from app.rb:1:in `<main>'

I am brand new to ruby so there is likely something stupid I am missing. Thanks in advance

**Comment by zamtech18** [comment]
Solved my own problem. It was something stupid. I needed to browse to my code directory and run `bundle install`

**Comment by bhavinjr** [comment]
I have same problem
```
bundle install


Using concurrent-ruby 1.0.5
Using i18n 0.8.4
Using minitest 5.10.2
Using thread_safe 0.3.6
Using tzinfo 1.2.3
Using activesupport 5.1.1
Using activemodel 5.1.1
Using arel 8.0.0
Using activerecord 5.1.1
Using builder 3.2.3
Using activemodel-serializers-xml 1.0.1
Using activeresource 5.0.0
Using bundler 1.17.3
Using dotenv 2.2.1
Using multi_xml 0.6.0
Using httparty 0.15.5
Using mustermann 1.0.0
Using rack 2.0.3
Using rack-protection 2.0.0
Using shopify_api 4.9.0
Using tilt 2.0.7
Using sinatra 2.0.0
Bundle complete! 4 Gemfile dependencies, 22 gems now installed.
Bundled gems are installed into `./vendor/bundle`
```

```
ruby  01\ Getting\ Started/app.rb

Traceback (most recent call last):
	2: from 01 Getting Started/app.rb:1:in `<main>'
	1: from /usr/local/lib/site_ruby/2.5.0/rubygems/core_ext/kernel_require.rb:54:in `require'
/usr/local/lib/site_ruby/2.5.0/rubygems/core_ext/kernel_require.rb:54:in `require': cannot load such file -- shopify_api (LoadError)
```

can any one know how to solve that?
